name: Create docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Generate docs
        run: |
          pip install -r requirements.txt
          python ./scripts/docs.py > ./DOCUMENTATION.md
      - name: Push docs
        run: |
          if [ -z "$(git status --porcelain)" ]; then exit 0; fi
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add ./DOCUMENTATION.md
          git commit -m "chore: generate documentation"
          git push